### ISSUE TITLE
Error getting last messages: 'RoomMessageText' object has no attribute 'type'

### ISSUE THREAD

**Issue by dillfrescott** [kumitterer/matrix-gptbot#5]
[2024-04-10 13:31:37:555366] - process_query - [ERROR] Error getting last messages: 'RoomMessageText' object has no attribute 'type'

it happens every time

**Comment by kumitterer** [comment]
Hi, thank you very much for reporting this issue!

Seems like something changed upstream so that we can't get the type of an event the way we used to anymore – I have applied a fix for this (cece8cfb24e6f2e98d80d233b688c3e2c0ff05ae), and released it as v0.3.6.

Can you please update to the latest release (if you installed from pypi, you can just do `pip install -U matrix-gptbot`, or just pull and install the repo) and check if that fixes the issue for you? I'm closing the issue for now, feel free to reopen if you're still having trouble!

**Comment by dillfrescott** [comment]
Sure! Thank you for the response!
